version: '3'
services:
  node:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: solid-driver-users
    volumes:
      - .:/app
  pushpin:
    image: fanout/pushpin:1.28.0
    environment:
      target: node:3000
    ports:
      - 3000:7999
      - 5561:5561
