version: '3'

services:
  node:
    build:
      context: .
      dockerfile: prod.dockerfile
    image: solid-drive-users
    environment:
      NODE_ENV: production
      PROD_PORT: 4000
    depends_on:
      - pushpin
  pushpin:
    image: fanout/pushpin:1.28.0
    environment:
      target: node:4000
    ports:
      - 80:7999
