version: '3'
services:
  node:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: solid-driver-users
    environment:
      NODE_ENV: development
      DEV_PORT: 4000
      DEV_DB_HOST: db
      DEV_DB_USER: solid
      DEV_DB_PASSWORD: solid
      DEV_DB_NAME: solid_drive
      DEV_PUSHPIN_PUBLISH: http://pushpin:5561/publish
      DEV_REDIS_DB: 0
      DEV_REDIS_PORT: 6379
      DEV_REDIS_HOST: redis
      DEV_JWT_SECRET: cd9fb2add38b1793efce43e9d00f9eb0d3698b6e231765d5ec7212bcb3573bbd07ce1625aa7280371fe65bc5701ed36ce0af6d26eda59d6169e39310b5fdab4f
      DEV_EMAIL_USER: soliddrive@outlook.com.br
      DEV_EMAIL_PASSWORD: # email password
      DEV_DOMAIN_URL: http://localhost:4000
    volumes:
      - .:/app
      - app/node_modules
    ports:
      - 9229:9229
    depends_on:
      - pushpin
      - db
  pushpin:
    image: fanout/pushpin:1.28.0
    environment:
      target: node:4000
    ports:
      - 4000:7999
  db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_DATABASE: solid_drive
      MYSQL_USER: solid
      MYSQL_PASSWORD: solid
      MYSQL_ROOT_PASSWORD: solid
    volumes:
      - /mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:6.0.2
    ports:
      - 6379:6379
