'use strict'

const EMAIL_FIELD = 'email'
const USERNAME_FIELD = 'username'
const PASSWORD_FIELD = 'password'

const WHITE_SPACES = /\s/g
const USERNAME_MAX_LENGTH = 30
const EMAIL_MAX_LENGTH = 120
const EMAIL_PATTERN = /[a-z0-9_.]+@([a-z]+\.)[a-z{2}]+(\.([a-z]{2}))?$/
const PASSWORD_MAX_LENGTH = 22
const PASSWORD_MIN_LENGTH = 8
const NUMBERS_PATTERN = /[0-9]+/
const LETTERS_PATTERN = /[a-zA-Z]+/
const SPECIAL_CHARACTER_PATTERN = /[\W]+/
const PASSWORD_PATTERN = /^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*\W)[a-zA-Z0-9-_\W]+$/

const MISSING_PARAMETER_CODE = 'user0'
const INVALID_PARAMETER_CODE = 'user1'

const WHITE_SPACES_CODE = 'whiteSpaces'
const MAX_LENGTH_CODE = 'maxLength'
const MIN_LENGTH_CODE = 'minLength'
const UNIQUE_CODE = 'unique'
const NOT_CONTAIN_LETTERS = 'letters'
const NOT_CONTAIN_NUMBERS = 'numbers'
const NOT_CONTAIN_SPECIAL_CHARACTER = 'specialCharacter'

const USER_REQUIRED_PARAMETERS = [EMAIL_FIELD, USERNAME_FIELD, PASSWORD_FIELD]

const MESSAGES = {
  [MISSING_PARAMETER_CODE]: 'Missing required parameter',
  [INVALID_PARAMETER_CODE]: 'Invalid parameter',
  [WHITE_SPACES_CODE]: 'Cannot contain white spaces',
  [MAX_LENGTH_CODE]: 'Exceed maximum allowed length',
  [MIN_LENGTH_CODE]: 'Have fewer characters than the minimum required',
  [UNIQUE_CODE]: 'Must be unique',
  [NOT_CONTAIN_LETTERS]: 'Must contain letters',
  [NOT_CONTAIN_NUMBERS]: 'Must contain numbers',
  [NOT_CONTAIN_SPECIAL_CHARACTER]: 'Must contain special character'
}

exports.EMAIL_FIELD = EMAIL_FIELD
exports.USERNAME_FIELD = USERNAME_FIELD
exports.PASSWORD_FIELD = PASSWORD_FIELD

exports.WHITE_SPACES = WHITE_SPACES
exports.USERNAME_MAX_LENGTH = USERNAME_MAX_LENGTH
exports.EMAIL_MAX_LENGTH = EMAIL_MAX_LENGTH
exports.EMAIL_PATTERN = EMAIL_PATTERN
exports.PASSWORD_MAX_LENGTH = PASSWORD_MAX_LENGTH
exports.PASSWORD_MIN_LENGTH = PASSWORD_MIN_LENGTH
exports.LETTERS_PATTERN = LETTERS_PATTERN
exports.NUMBERS_PATTERN = NUMBERS_PATTERN
exports.SPECIAL_CHARACTER_PATTERN = SPECIAL_CHARACTER_PATTERN
exports.PASSWORD_PATTERN = PASSWORD_PATTERN

exports.INVALID_PARAMETER_CODE = INVALID_PARAMETER_CODE
exports.MISSING_PARAMETER_CODE = MISSING_PARAMETER_CODE

exports.WHITE_SPACES_CODE = WHITE_SPACES_CODE
exports.MAX_LENGTH_CODE = MAX_LENGTH_CODE
exports.MIN_LENGTH_CODE = MIN_LENGTH_CODE
exports.UNIQUE_CODE = UNIQUE_CODE
exports.NOT_CONTAIN_LETTERS = NOT_CONTAIN_LETTERS
exports.NOT_CONTAIN_NUMBERS = NOT_CONTAIN_NUMBERS
exports.NOT_CONTAIN_SPECIAL_CHARACTER = NOT_CONTAIN_SPECIAL_CHARACTER

exports.USER_REQUIRED_PARAMETERS = USER_REQUIRED_PARAMETERS

exports.MESSAGES = MESSAGES
