name: CI

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.0.0'
    - run: npm ci
    - run: npm test
